#!/bin/bash
# fix permissions to run the SWI-Prolog website as www-data, group www-data

groupshared()
{ chgrp -R www-data .
  find . -type d | xargs chmod 2775
  find refs -type f | xargs chmod 664
  git config core.sharedRepository group
}

fixwiki()
{ git config user.email "wiki@swi-prolog.org"
  git config user.name "Wiki manager"
  chgrp -R www-data .
  find . -name '*.txt' | xargs chmod 664
  find . -type d | xargs chmod 2775
  (cd `git rev-parse --git-dir` && groupshared)
}

fixerepo()
{ ( chgrp -R www-data .
    find . -type f | xargs chmod 664
    find . -type d | xargs chmod 2775
    (cd `git rev-parse --git-dir` && groupshared)
  )
}

for repo in www examples blog; do
  [ -d data/git/$repo ] || git clone https://github.com/SWI-Prolog/plweb-$repo.git data/git/$repo
done

(cd data/git/www && fixwiki)
(cd data/git/blog && fixrepo)
(cd data/git/examples && fixrepo)

# Create and fix the logfile permissions
datadirs="data/log data/pack"

for d in $datadirs; do
  mkdir -p $d
  chgrp -R www-data $d
  find $d  -type d | xargs chmod 2775
done

# Make the database writeable
chgrp www-data data/*.db
chmod 664 data/*.db

[ -d data/private/etc/ssh ] || mkdir -p data/private/etc/ssh
[ -f data/private/etc/ssh/authorized_keys ] || touch data/private/etc/ssh/authorized_keys
[ -f data/private/etc/ssh/ssh_host_ecdsa_key ] || ssh-keygen -A -f data/private
